### ISSUE TITLE
Wrong button variables on Step 7 & 8

### ISSUE THREAD

**Issue by octogene** [googlecodelabs/android-kotlin-animation-property-animation#1]
Step 7, in the `fader` method, the line `animator.disableViewDuringAnimation(fade)` should be replaced by `animator.disableViewDuringAnimation(fadeButton)`

Step 8, in the `colorizer` method, the line `animator.disableViewDuringAnimation(bgColor)` should be replaced by `animator.disableViewDuringAnimation(colorizeButton)`

**Comment by chethaase** [comment]
Sorry I missed this when you filed it - there were a few related naming problems resulting from a refactor I did recently. Should be fixed now.
