### ISSUE TITLE
 Advanced Android in Kotlin: Property Animation 3.1 [Step #][description]

### ISSUE THREAD

**Issue by AliAkberAakash** [googlecodelabs/android-kotlin-animation-property-animation#2]
**Describe the problem**
A typing mistake. Variable name called wrong. It should be **fadeButton** instead of **fade**.

**In which lesson and step of the codelab can this issue be found?**
Lesson 03.1 + step 7

**How to reproduce?**
just copy and paste the code of this codelab.

**Versions**
1. What version of Android Studio are you using?
28
2. What API level are you targeting?
28

**codelab:** advanced-android-kotlin

**Comment by chethaase** [comment]
Thanks, that's a bug from a recent refactor where I made the code names better but neglected to update the codelab in the right places. (There are actually a few related naming issues that I found while looking at this). Updating soon.

**Comment by chethaase** [comment]
Should be fixed now (reload the codelab)
